# This workflow will install Python dependencies, run tests,
# and report test results and code coverage as artifacts. It will
# be called by the workflow that run tests against new PRs and as
# a first step in the workflow that publishes new Docker images.

name: A reusable workflow to build and run the unit test suite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/reusable_python_and_poetry_setup.yaml

      - name: Install package
        run: poetry install

      - name: Run linting
        run: |
          poetry run ruff batcher

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest >& test_results.txt
        # poetry run pytest tests/test_filename_grouping.py >& test_results.txt
        # TODO: expand tests to include full concatenation runs, i.e., don't just run test_group_handling.py

      - name: Generate coverage report
        if: ${{ always() }}
        run: |
          poetry run coverage report -m >& coverage_report.txt
          poetry run coverage html --dir htmlcov

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test result
          path: test_results.txt

      - name: Archive code coverage report (plain text)
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: code coverage report (plain text)
          path: coverage_report.txt

      - name: Archive code coverage report (HTML)
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: code coverage report (HTML)
          path: htmlcov/*
