# This workflow will install Python and Poetry.
name: A reusable workflow to build the repo

on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.3.2
