# This workflow will install Python dependencies, run tests,
#   and report test results and code coverage as artifacts. It will
#   be called by the workflow that runs tests against new PRs and as
#   a first step in the workflow that publishes new Docker images.

name: A reusable workflow to build and run the unit test suite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    name: Python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.3.2

      - name: Install package
        run: poetry install

      - name: Lint
        run: |
          poetry run ruff batcher

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=batcher --cov-report=xml:build/reports/coverage.xml --cov-report=html:build/reports/coverage.html tests/

      - name: Archive code coverage report (xml)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: code coverage report (xml)
          path: build/reports/coverage.xml

      - name: Archive code coverage report (HTML)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: code coverage report (HTML)
          path: build/reports/coverage.html
